services:
  - type: web
    name: cte-scheduling
    env: php
    repo: https://github.com/KingSaludez/cte-scheduling
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_DATABASE
        fromDatabase:
          name: cte-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: cte-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cte-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: cte-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cte-db
          property: port
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan key:generate
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT

databases:
  - name: cte-db
    plan: free
    databaseName: cte_scheduling
    region: singapore
