services:
  - type: web
    name: cte-scheduling
    runtime: docker
    repo: https://github.com/KingSaludez/cte-scheduling
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: cte-db
          property: connectionString
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync

databases:
  - name: cte-db
    plan: free
    databaseName: cte_scheduling
    region: singapore
